### ISSUE TITLE
Exception while crawling doc file

### ISSUE THREAD

**Issue by wazhar** [leechcrawler/leech#3]
Hi, 

I got this exception while crawling directory with single .doc file. 
java.lang.ClassNotFoundException: org.apache.http.util.Args.

Adding the following dependency to the maven build resoles the issue. 

            <dependency>
                <groupId>org.apache.httpcomponents</groupId>
                <artifactId>httpcore</artifactId>
                <version>4.4</version>
            </dependency>

Thanks,
Wazhar

**Comment by reuschling** [comment]
Thanks for the hint, fixed in leechcrawler 1.8.1
best
Chris
