### ISSUE TITLE
OfficeParser fails on embedded images associated with Microsoft Photo Editor

### ISSUE THREAD

**Issue by wazhar** [leechcrawler/leech#4]
Crawling word document is failing with following exception 

org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser

Try same document with Tika 1.8 directly and it does not fail. I will attach the document. 

WAzhar

**Comment by wazhar** [comment]
Here is the document. https://www.dropbox.com/s/ts9sv9t1c7zk2zg/simple.doc?dl=0

**Comment by reuschling** [comment]
sorry for the long time, the message was lost. Is this issue still the case with the current version, or can it be closed? The file link is not valid anymore, so I can not check it.
best
Christian

**Comment by wazhar** [comment]
Problem exists in the current version as well. 

Here is the link : https://www.dropbox.com/s/yhaftxhkjriu1wf/picture.doc?dl=0

**Comment by reuschling** [comment]
bug is fixed, created new version 1.10.1. Thanks for support, Wazhar.

**Comment by wazhar** [comment]
Verified with 1.10.1. It works.

Thanks
