### ISSUE TITLE
Possible memory leak 

### ISSUE THREAD

**Issue by wazhar** [leechcrawler/leech#8]
I noticed several instances of  'de.dfki.km.leech.parser.incremental.IncrementCrawlingHistory' remains in memory and never get garbage collected. After bit of an investigation it seems an instance is created per session and sticks to memory forever. 

Please  refer to the attached screenshot.

Thanks.
![screenshot_20180402_140842](https://user-images.githubusercontent.com/6858879/38193142-7b2dd2ec-3681-11e8-8daf-f6d86b30e0fb.png)

**Comment by reuschling** [comment]
Reuse your `CrawlerContext` Object - if you reuse it, the `IncrementalCrawlingHistory` Object will be created only once with `getIncrementalCrawlingHistory()`. You will have as many `IncrementalCrawlingHistory` instances as `CrawlerContext` instances.
